---
# tasks file for keepalived
- name: "Install"
  ansible.builtin.package:
    name: keepalived
    state: present

- name: "configuration file"
  template:
    src: "config.j2"
    dest: "/etc/keepalived/keepalived.conf"
  notify:
    - Restart keepalived

- name: Enable service keepalived
  ansible.builtin.systemd:
    name: keepalived
    enabled: true
    daemon_reload: true
    state: started
