---

- name: Firewall block
  block:
  - name: Copy Template firewall
    ansible.builtin.template:
      src: main.nft.j2
      dest: /etc/nftables.conf
    notify: load-new-config

  - name: Copy file to nftable.service
    ansible.builtin.copy:
      src: nftable.service
      dest: /etc/systemd/system/nftable.service

  - name: Enable service nftables
    ansible.builtin.systemd:
      name: nftables
      enabled: true
      daemon_reload: true
      state: started
  when: "'firewall' in hostvars[inventory_hostname]"
