## install exaBGP
- name: Install python package
  ansible.builtin.pip:
    name: exabgp

- name: Creates directory /etc/exabgp/
  file:
    path: /etc/exabgp/
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: "[exabgp] configuration file"
  template:
    src: "conf.ini.J2"
    dest: "/etc/exabgp/exabgp.conf"

- name: "[exabgp] route.py"
  template:
    src: "route.py.j2"
    dest: "/srv/route.py"
    mode: 0755

- name: Template a file to exabgp.service.j2
  ansible.builtin.template:
    src: exabgp.service.j2
    dest: /etc/systemd/system/exabgp.service
  register: touch_exabgp_service

- name: Enable service exabgp
  ansible.builtin.systemd:
    name: exabgp
    enabled: true
    daemon_reload: true
    state: restarted
  when: touch_exabgp_service.changed
