---
# tasks file for kube-apiserver
- name: Creates directory
  file:
    path: "/etc/kubernetes/config"
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Download file kube-apiserver
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v{{k8s_version}}/bin/linux/amd64/kube-apiserver"
    dest: /usr/local/bin/
    mode: 'u=rwx,g=rx,o=rx'
    checksum: sha256:https://dl.k8s.io/release/v{{k8s_version}}/bin/linux/amd64/kube-apiserver.sha256

- name: Template a file to kube-apiserver.service
  ansible.builtin.template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
  notify: Restart kube-apiserver

- name: Template a file to encryption-config.yaml
  ansible.builtin.template:
    src: encryption-config.yaml.j2
    dest: /etc/kubernetes/encryption-config.yaml
  notify: Restart kube-apiserver

- name: Enable service kube-apiserver
  ansible.builtin.systemd:
    name: kube-apiserver
    enabled: true
    daemon_reload: true
    state: started
