- name: Module Load for containerd
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/containerd.conf

- name: Add the overlay
  modprobe:
    name: overlay
    state: present

- name: Add the br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: sysctl for k8s-cri
  copy:
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
  notify:
    - sysctl--system

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: swapoff -a
