- name: Add repositories key
  apt_key:
    url: '{{ item.url }}'
    state: present
  loop: '{{ repositories }}'

- name: Add repositories
  apt_repository:
    repo: '{{ item.repo }}'
    state: present
    filename: '{{ item.filename }}'
  loop: '{{ repositories }}'
