---
# tasks file for nginx

- name: Install
  ansible.builtin.apt:
    update_cache: yes
    allow_change_held_packages: true
    pkg:
      - nginx

- name: Enable service and started
  ansible.builtin.systemd:
    name: nginx.service
    enabled: true
    daemon_reload: true
    state: started

- name: nginx - vhost
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: /etc/nginx/sites-enabled/{{item.name}}.vhost.cfg
  loop: "{{nginx.vhost}}"
  notify: Restart-Nginx
