---
- name: Copy cloud-controller-manager config
  ansible.builtin.template:
    src: ccm-config.j2
    dest: /etc/kubernetes/config/ccm-config.ini

- name: Copy cloud-controller-manager-sa-role
  ansible.builtin.template:
    src: cloud-controller-manager-sa-role.yml
    dest: /etc/kubernetes/config/cloud-controller-manager-sa-role.yml

- name: kubectl apply cloud-controller-manager-sa-role
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/config/cloud-controller-manager-sa-role.yml
  ignore_errors: true
  run_once: true

- name: Manifest ccm
  ansible.builtin.template:
    src: manifest.yml.j2
    dest: /etc/kubernetes/manifests/ccm.yml
  delegate_to: "{{ groups.init[0] }}"
  run_once: true
