---
# tasks file for calico
- name: Creates directory
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  loop:
    - /etc/cni
    - /opt/cni
    - /etc/cni/net.d
    - /opt/cni/bin

- name: Download files
  ansible.builtin.get_url:
    url: "{{item}}"
    dest: /usr/local/bin/
    mode: "u=rwx,g=rx,o=rx"
  loop:
    - https://github.com/containernetworking/plugins/releases/download/v1.3.0/cni-plugins-linux-amd64-v1.3.0.tgz
  register: touchcni

- name: tar cni
  ansible.builtin.command: tar zxvf /usr/local/bin/cni-plugins-linux-amd64-v1.3.0.tgz -C /opt/cni/bin/
  when:
    - touchcni.changed

- name: "KubeConfig calico-cni"
  ansible.builtin.include_tasks:
    file: ./_share/_.kubeconfig.yml
  vars:
    _name: "{{element._name}}"
    _crt: "{{element._crt}}"
    _IP: "{{KUBERNETES_PUBLIC_ADDRESS}}"
  loop:
    - { _name: "calico-cni", _crt: "calico-cni" }
  loop_control:
    loop_var: element

- name: Download files /opt/cni/bin/calico
  ansible.builtin.get_url:
    url: https://github.com/projectcalico/cni-plugin/releases/download/v{{calico_version_cni}}/calico-amd64
    dest: /opt/cni/bin/calico
    mode: "u=rwx,g=rx,o=rx"
- name: Download files /opt/cni/bin/calico-ipam
  ansible.builtin.get_url:
    url: https://github.com/projectcalico/cni-plugin/releases/download/v{{calico_version_cni}}/calico-ipam-amd64
    dest: /opt/cni/bin/calico-ipam
    mode: "u=rwx,g=rx,o=rx"

- name: Template a file to 10-calico.conflist
  ansible.builtin.copy:
    src: 10-calico.conflist
    dest: /etc/cni/net.d/10-calico.conflist
  notify:
    - Restart-service-containerd
