- name: Add repositories key docker
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Add repositories docker
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
    state: present
    filename: "docker"

- name: Install
  ansible.builtin.apt:
    state: latest
    update_cache: true
    allow_change_held_packages: true
    pkg:
      - docker
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: enable local api http
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: '^ExecStart=/usr/bin/dockerd '
    line: ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock -H tcp://127.0.0.1:5555
  notify:
    - Restart-systemd
    - Restart-service-docker

- name: copy config
  ansible.builtin.copy:
    src: docker
    dest: /etc/docker/daemon.json
  notify:
    - Restart-systemd
    - Restart-service-docker
