# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
{% set all = [] %}

{% for host in groups['all'] %}
{% set all= all.append('{0}:9100'.format(host)) %}
{% endfor %}

{% set etcd = [] %}

{% for worker in groups['etcd'] %}
{% set etcd= etcd.append('{0}:2379'.format(worker)) %}
{% endfor %}

scrape_configs:
## DOTO sd for kubernetes
  - job_name: k8s
    kubernetes_sd_configs:
    - role: node
      kubeconfig_file: /etc/prometheus/k8s.kubeconfig
    scheme: https
    # tls_config:
    #   insecure_skip_verify: true
  - job_name: all_host
    static_configs:
    - targets: [ {{ all | join(",") }} ]
  - job_name: etcd
    scheme: https
    tls_config:
        ca_file: /etc/etcd/ssl/ETCD_CA.pem
        cert_file: /etc/etcd/ssl/check_health.pem
        key_file: /etc/etcd/ssl/check_health.key
    static_configs:
    - targets: [ {{etcd | join(",")}} ]
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["127.0.0.1:9090"]
