---
# tasks file for podman
- name: Install podman
  ansible.builtin.apt:
    state: latest
    update_cache: true
    allow_change_held_packages: true
    pkg:
      - podman

- name: Template loop
  ansible.builtin.template:
    src: container.service.j2
    dst: /home/{{ item.user }}/.config/systemd/user
  loop: "{{ podmans }}"

