- name: Copy argo_app.yml
  ansible.builtin.copy:
    src: argo_app.yml
    dest: /etc/kubernetes/config/argo_app.yml
    owner: root
    group: root
    mode: '0644'
    backup: yes
  register: touch_argo_app_yml

- name: kubectl apply argo_app.yml
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/config/argo_app.yml
  when: touch_argo_app_yml.changed
  ignore_errors: true
  run_once: true
  tags: [mini]

- name: Copy argo_ingress.yml
  ansible.builtin.copy:
    src: argo_ingress.yml
    dest: /etc/kubernetes/config/argo_ingress.yml
    owner: root
    group: root
    mode: '0644'
    backup: yes
  register: touch_argo_ingress_yml

- name: kubectl apply argo_ingress.yml
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/config/argo_ingress.yml
  when: touch_argo_ingress_yml.changed
  ignore_errors: true
  run_once: true
