
- name: Download files
  ansible.builtin.get_url:
    url: https://github.com/projectcalico/calico/releases/latest/download/calicoctl-linux-amd64
    dest: /usr/local/bin/calicoctl
    mode: 'u=rwx,g=rx,o=rx'

- name: calicoctl - test
  ansible.builtin.shell: calicoctl get nodes --allow-version-mismatch
  register: calicoctl_output
  environment:
    DATASTORE_TYPE: kubernetes

- name: debug calicoctl
  debug:
    msg: "{{ calicoctl_output.stdout_lines }}"

- name: Template a file to calico_IPPool_address.yml
  ansible.builtin.template:
    src: calico_IPPool_address.yml.j2
    dest: /etc/kubernetes/config/calico_IPPool_address.yml
  register: touch_calico_IPPool_address

- name: calicoctl get ippools
  ansible.builtin.shell: calicoctl get ippools --allow-version-mismatch
  register: calicoctl_output
  environment:
    DATASTORE_TYPE: kubernetes

- name: debug calicoctl
  debug:
    msg: "{{ calicoctl_output.stdout_lines }}"

- name: calicoctl create -f /etc/kubernetes/config/calico_IPPool_address.yml
  ansible.builtin.shell: calicoctl create -f /etc/kubernetes/config/calico_IPPool_address.yml --allow-version-mismatch
  run_once: true
  environment:
    DATASTORE_TYPE: kubernetes
  ignore_errors: true
