- name: Get local kubeconfig
  ansible.builtin.fetch:
    src: /root/.kube/config
    dest: ~/.kube
    flat: true
  delegate_to: "{{ groups.init[0] }}"
  ignore_errors: true
  run_once: true

- ansible.builtin.import_tasks: _02_k8s.yml
- ansible.builtin.import_tasks: _03_calico.yml

- ansible.builtin.import_tasks: 00.yml
  delegate_to: "{{ groups.init[0] }}"
  run_once: true

- name: Block ArgoCD
  tags: [ArgoCD]
  block:
    - ansible.builtin.import_tasks: 03_argocd.yml
      delegate_to: "{{ groups.init[0] }}"
      run_once: true

    - ansible.builtin.import_tasks: 04_deploy_app.yml
      delegate_to: "{{ groups.init[0] }}"
      run_once: true
