---
# handlers file for containerd
  - name: sysctl--system
    ansible.builtin.shell: sysctl --system

  - name: Restart-service-containerd
    ansible.builtin.service:
      name: containerd
      state: restarted
