- name: Creates directory loop
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: '0700'
  loop:
    - /root/.kube/
    - /etc/kubernetes/config

- name: "{{element._name}}"
  include_tasks:
    file: ./_share/_.kubeconfig.yml
  vars:
    _name: "{{element._name}}"
    _crt: "{{element._crt}}"
    _IP: "{{KUBERNETES_PUBLIC_ADDRESS}}"
  loop:
    - {_name: 'system:kube-proxy',_crt: "kube-proxy"}
    - {_name: 'system:kube-controller-manager',_crt: "kube-controller-manager"}
    - {_name: 'system:kube-scheduler',_crt: "kube-scheduler"}
    - {_name: 'admin',_crt: "admin"}
  loop_control:
    loop_var: element

- name: Copy /root/.kube/config
  ansible.builtin.copy:
    src: /etc/kubernetes/config/admin.kubeconfig
    dest: /root/.kube/config
    mode: '0700'
    remote_src: yes
