---
# tasks file for kubelet

- name: Check that the kubectl exist
  ansible.builtin.stat:
    path: /usr/local/bin/kubectl
  register: stats_kubectl

- name: Download file kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v{{ k8s_version }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/
    mode: "u=rwx,g=rx,o=rx"
    checksum: sha256:https://dl.k8s.io/release/v{{ k8s_version }}/bin/linux/amd64/kubectl.sha256
  when: not stats_kubectl.stat.exists

- name: Check that the kubelet exist
  ansible.builtin.stat:
    path: /usr/local/bin/kubelet
  register: stats_kubelet

- name: Download file kubelet
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v{{ k8s_version }}/bin/linux/amd64/kubelet"
    dest: /usr/local/bin/
    mode: "u=rwx,g=rx,o=rx"
    checksum: sha256:https://dl.k8s.io/release/v{{ k8s_version }}/bin/linux/amd64/kubelet.sha256
  when: not stats_kubelet.stat.exists

- name: Creates directory /etc/kubernetes/*
  file:
    path: "{{item}}"
    state: directory
    recurse: true
    owner: root
    group: root
    mode: "0700"
  loop:
    - "/etc/kubernetes/manifests"
    - "/etc/kubernetes/config"

- name: "KubeConfig Kube-proxy"
  include_tasks:
    file: ./_share/_.kubeconfig.yml
  vars:
    _name: "{{element._name}}"
    _crt: "{{element._crt}}"
    _IP: "{{KUBERNETES_PUBLIC_ADDRESS}}"
  loop:
    - { _name: "system:node:{{hostname}}", _crt: "node_{{hostname}}" }
  loop_control:
    loop_var: element

- name: Creates directory /var/lib/kubelet/
  file:
    path: /var/lib/kubelet/
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Template a file to kubelet-config.yaml
  ansible.builtin.template:
    src: kubelet-config.yaml.j2
    dest: /var/lib/kubelet/kubelet-config.yaml
  notify: Restart-service-kubelet

- name: Template a file to kubelet.service.j2
  ansible.builtin.template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify: Restart-service-kubelet

- name: Enable service kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
    daemon_reload: true
    state: started
