- name: "[HAPROXY] Install"
  ansible.builtin.package:
    name: haproxy
    state: present
    update_cache: yes

- name: "[HAPROXY] Enable service haproxy"
  ansible.builtin.systemd:
    name: haproxy
    enabled: true
    daemon_reload: true

- name: "[HAPROXY] configuration file"
  template:
    src: "config.j2"
    dest: "/etc/haproxy/haproxy.cfg"
  notify:
    - Restart Haproxy

- name: Enable service haproxy
  ansible.builtin.systemd:
    name: haproxy
    enabled: true
    daemon_reload: true
    state: started
