- name: "[{{hostname}}] kubernetes SAN"
  set_fact:
    static:
      - "DNS:kubernetes"
      - "DNS:kubernetes.default"
      - "DNS:kubernetes.default.svc"
      - "DNS:kubernetes.default.svc.cluster"
      - "DNS:kubernetes.default.svc.{{domain}}"
      - "DNS:kubernetes.svc.cluster.local"
      - "DNS:kubernetes.svc.{{domain}}"
      - "IP:127.0.0.1"
      - "IP:{{clusterIP}}"
      - "IP:{{KUBERNETES_PUBLIC_ADDRESS}}"
    dynamic: "{{groups['controlplane'] | fix_to_san}}"

- name: "[{{hostname}}] etcd SAN"
  set_fact:
    dynamic_etcd: "{{groups['etcd'] | fix_to_san}}"

- name: "[{{hostname}}] {{item.common_name}}"
  include_tasks:
    file: ./_share/_sign.yml
  vars:
    _path_key: "{{CERT_PATH}}/{{item.name}}.key"
    _path_crt: "{{CERT_PATH}}/{{item.name}}.pem"
    _common_name: "{{item.common_name}}"
    _organization_name: "{{item.organization_name}}"
    _ca_key: "{{ hostvars['INIT_CA_HOST'][item.ca]['key']['source'] }}"
    _ca_pem: "{{ hostvars['INIT_CA_HOST'][item.ca]['crt']['source'] }}"

    _subject_alt_name: "{{ item.subject_alt_name | default([]) }}"
  loop:
    - { name: 'kube-controller-manager', common_name: 'system:kube-controller-manager' , ca: 'share_Kubernetes_CA', organization_name: 'system:kube-controller-manager'}
    - { name: 'kube-proxy', common_name: 'system:kube-proxy' , ca: 'share_Kubernetes_CA', organization_name: "system:node-proxier"}
    - { name: 'kube-scheduler', common_name: 'system:kube-scheduler' , ca: 'share_Kubernetes_CA' , organization_name: 'system:kube-scheduler'}
    - { name: 'service-accounts', common_name: 'service-accounts' , ca: 'share_Kubernetes_CA' , organization_name: 'service-accounts'}
    - { name: 'calico-cni', common_name: 'calico-cni' , ca: 'share_Kubernetes_CA' , organization_name: 'calico-cni'}
    - { name: 'admin', common_name: 'admin' , ca: 'share_Kubernetes_CA', organization_name: "system:masters"}
    - { name: 'kubernetes', common_name: 'kubernetes' , ca: 'share_Kubernetes_CA', organization_name: "system:masters", subject_alt_name: "{{ static + dynamic }}"}
    # Calico_Typha_CA
    - { name: 'typha', common_name: 'calico-typha' , ca: 'share_ca_typha', organization_name: 'calico:typha'}
    - { name: 'calico-node', common_name: 'calico-node' , ca: 'share_ca_typha', organization_name: 'calico:node'}
    # ca_etcd
    - { name: 'etcd-cluster', common_name: 'etcd-cluster' , ca: 'share_ETCD_CA', organization_name: 'etcd-cluster', subject_alt_name: "{{ dynamic_etcd  }}" }
    - { name: 'kube-api-client', common_name: 'kube-api-client' , ca: 'share_ETCD_CA', organization_name: 'etcd-cluster'}
    - { name: 'prometheus', common_name: 'prometheus' , ca: 'share_ETCD_CA', organization_name: 'monigoring'}
