---

  - name: Write certificate {{item.key}}
    copy:
      dest: "{{ item.value['crt']['source'] }}"
      content: "{{ item.value['crt']['content']|b64decode }}"
    loop: "{{hostvars['INIT_CA_HOST'] | dict2items}}"
    when: '"share_" in item["key"]'

  - name: Write key {{item.key}}
    copy:
      dest: "{{ item.value['key']['source'] }}"
      content: "{{ item.value['key']['content']|b64decode }}"
    loop: "{{hostvars['INIT_CA_HOST'] | dict2items}}"
    when: '"share_" in item["key"]'
