
- name: Install autofs
  ansible.builtin.apt:
    name: autofs
    state: latest
    update_cache: yes

- name: "configuration file auto.master"
  template:
    src: "auto.master.j2"
    dest: "/etc/auto.master"
  notify: Restart-autofs

- name: "configuration file auto-map"
  template:
    src: "auto-map.j2"
    dest: "/etc/auto-map"
  notify: Restart-autofs

- name: Enable service autofs
  ansible.builtin.systemd:
    name: autofs
    enabled: true
    daemon_reload: true
    state: started
