- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
  tags: TEMPLATE

- name: Config Remote syslog Server
  copy:
    src: 10_remote_syslog.conf
    dest: /etc/rsyslog.d/10_remote.conf
  when: "inventory_hostname not in groups['syslog']"
  notify:
    - Restart rsyslog
  tags: LOG

- name: Force all notified handlers to run at this point, not waiting for normal sync points
  ansible.builtin.meta: flush_handlers

- name: Install Default Software
  ansible.builtin.apt:
    pkg:
      - resolvconf

- name: Template a file to head.j2
  ansible.builtin.template:
    src: head.j2
    dest: /etc/resolvconf/resolv.conf.d/head
  register: touch_tail

- name: resolvconf  -u
  ansible.builtin.command: resolvconf  -u
  when:
    - touch_tail.changed

- name: Install Default Software
  ansible.builtin.apt:
    pkg:
      - tcpdump
      - gpg
      - python3-pip
      - net-tools
      - socat
      - conntrack
      - ipset
      - curl
      - sudo
      - chrony
      - clevis
      - clevis-luks
      - clevis-initramfs
    state: latest
    update_cache: true
  tags: TEMPLATE

- name: Start service chrony, if not started
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true
  tags: TEMPLATE

- name: install apt by OS
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items: "{{ common.pkg }}"
  when: common.pkg is defined
  tags: TEMPLATE

- name: Install pip by OS
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items: "{{ common.pip }}"
  when: common.pip is defined
  tags: TEMPLATE
