---
# vars file for swift
def_soft_Debian:
      - parted
      - curl
      - gcc
      - memcached
      - rsync
      - sqlite3
      - xfsprogs
      - git-core
      - libffi-dev
      - liberasurecode-dev
      - libssl-dev
      - python3-setuptools
      - python3-coverage
      - python3-dev
      - python3-nose
      - python3-xattr
      - python3-eventlet
      - python3-greenlet
      - python3-pastedeploy
      - python3-netifaces
      - python3-pip
      - python3-dnspython
      - python3-mock
