- name: Creates directory
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: '0700'
  loop:
    - /etc/cni
    - /opt/cni
    - /etc/cni/net.d
    - /opt/cni/bin

- name: Download files
  ansible.builtin.get_url:
    url: "{{item}}"
    dest: /usr/local/bin/
    mode: 'u=rwx,g=rx,o=rx'
  loop:
    - https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz
  register: touchcni

- name: tar cni
  ansible.builtin.command: tar zxvf /usr/local/bin/cni-plugins-linux-amd64-v0.9.1.tgz -C /opt/cni/bin/
  when:
    - touchcni.changed

- name: Template a file to 10-bridge.conf
  ansible.builtin.copy:
    src: 10-bridge.conf
    dest: /etc/cni/net.d/10-bridge.conf
  notify:
    - Restart-service-containerd


- name: Template a file to 99-loopback.conf
  ansible.builtin.template:
    src: 99-loopback.conf.j2
    dest: /etc/cni/net.d/99-loopback.conf
  notify:
    - Restart-service-containerd
