- name: Module Load for containerd
  copy:
    content: |
      overlay
      br_netfilter
      ip_conntrack
    dest: /etc/modules-load.d/containerd.conf

- name: modprobe
  modprobe:
    name: "{{item}}"
    state: present
  loop:
    - ip_conntrack
    - br_netfilter
    - overlay

- name: sysctl for k8s-cri
  copy:
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.netfilter.nf_conntrack_max = 262144
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
  notify:
    - sysctl--system
