- name: install nfs
  ansible.builtin.package:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Directory
  ansible.builtin.file:
    path: "/var/nfs/{{ item }}"
    state: directory
    recurse: true
  loop:
    - storage1
    - all

- name: nfs exports
  ansible.builtin.template:
    src: exports.j2
    dest: "/etc/exports"
  notify: Restart nfs-kernel-server
