---
# tasks file for kube-controller-manager

- name: Download files
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v{{k8s_version}}/bin/linux/amd64/kube-controller-manager"
    dest: /usr/local/bin/
    mode: 'u=rwx,g=rx,o=rx'
    checksum: sha256:https://dl.k8s.io/release/v{{k8s_version}}/bin/linux/amd64/kube-controller-manager.sha256

- name: Creates directory /etc/kubernetes/config
  file:
    path: "/etc/kubernetes/config"
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Template a file to kube-controller-manager.kubeconfig
  ansible.builtin.template:
    src: kubeconfig.j2
    dest: /etc/kubernetes/config/kube-controller-manager.kubeconfig
  notify: Restart kube-controller-manager


- name: Template a file to kube-controller-manager.service
  ansible.builtin.template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
  notify: Restart kube-controller-manager


- name: Enable service kube-controller-manager
  ansible.builtin.systemd:
    name: kube-controller-manager
    enabled: true
    daemon_reload: true
