---
# tasks file for vault

- name: Add repositories key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present


- name: Add repositories
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com bullseye main'
    state: present
    filename: 'hashicorp.list'


- name: Install
  ansible.builtin.apt:
    update_cache: true
    allow_change_held_packages: true
    pkg:
      - vault

- name: Copy config
  ansible.builtin.template:
    src: config-vault.hcl
    dest: /etc/vault.d/vault.hcl
  notify:
    - Restart-service-vault

- name: Enable service and started
  ansible.builtin.systemd:
    name: vault.service
    enabled: true
    daemon_reload: true
    state: started

##



- name: "Add dumy Vault host"
  ansible.builtin.add_host:
    name: "INIT_Vault_HOST"
    keys: []
    root_token: false
  changed_when: false

- name: Block load secret
  delegate_to: '{{ groups.vault[0] }}'
  run_once: true
  block:
    - name: Check file
      ansible.builtin.stat:
        path: "/root/.secret"
      register: register_secret

    - name: Cat file
      ansible.builtin.shell: "cat /root/.secret"
      when: register_secret.stat.exists
      register: data

    - name: Set fact vault root_token
      ansible.builtin.set_fact:
        "root_token": "{{ data['stdout'] }}"
      delegate_to: "INIT_Vault_HOST"
      delegate_facts: true
      when: register_secret.stat.exists

    - name: Slurp hosts file
      ansible.builtin.slurp:
        src: /root/.secret1
      register: slurpfile
      when: register_secret.stat.exists

    - name: Parse
      ansible.builtin.set_fact:
        "keys": "{{ slurpfile['content'] | b64decode | regex_replace(\"'\", '\"') }}"
      delegate_to: "INIT_Vault_HOST"
      delegate_facts: true
      when: register_secret.stat.exists

    - name: Prep
      ansible.builtin.set_fact:
        "keys": "{{ hostvars['INIT_Vault_HOST']['keys']['keys'] }}"
      delegate_to: "INIT_Vault_HOST"
      delegate_facts: true
      when: register_secret.stat.exists

- name: GET status initialized
  ansible.builtin.uri:
    url: "https://127.0.0.1:8200/v1/sys/init"
    ca_path: /etc/ssl/Kubernetes_CA.pem
    method: GET
    validate_certs: false
    status_code: [429, 200, 501, 503]
    return_content: true
  register: output_status_initialized

- name: Status is false
  when: output_status_initialized['json']['initialized'] == false
  delegate_to: '{{ groups.vault[0] }}'
  run_once: true
  block:
    - name: B01:debug
      ansible.builtin.debug:
        var:  output_status_initialized['json']

    - name: vault init
      ansible.builtin.uri:
        url: "https://127.0.0.1:8200/v1/sys/init"
        ca_path: /etc/ssl/Kubernetes_CA.pem
        method: POST
        validate_certs: false
        status_code: [429, 200, 501, 503]
        return_content: true
        body_format: json
        body:
            "secret_shares": 1
            "secret_threshold": 1
      register: output_init_vault

    - name: set fact vault keys
      set_fact:
        "keys": "{{ output_init_vault['json']['keys'] | default([]) }}"
      delegate_to: "INIT_Vault_HOST"
      delegate_facts: true

    - name: set fact vault root_token
      set_fact:
        "root_token": "{{ output_init_vault['json']['root_token'] }}"
      delegate_to: "INIT_Vault_HOST"
      delegate_facts: true

    - name: Save secret
      template:
        src: secret.j2
        dest: "/root/.secret"

    - name: Save secret2
      template:
        src: payload.j2
        dest: "/root/.secret1"

    - name: Status output_init_vault
      ansible.builtin.debug:
        var: output_init_vault

    - name: Unseal
      ansible.builtin.uri:
        url: "https://127.0.0.1:8200/v1/sys/unseal"
        ca_path: /etc/ssl/Kubernetes_CA.pem
        method: POST
        validate_certs: false
        status_code: [429, 200, 501, 503]
        return_content: true
        body_format: json
        body:
            "key": "{{item}}"
      register: testUnseal
      loop: "{{ hostvars['INIT_Vault_HOST']['keys'] }}"

    - name: Make sure service has time to init
      ansible.builtin.pause:
        seconds: 20

- name: Seated - prgetint status
  ansible.builtin.uri:
    url: "https://127.0.0.1:8200/v1/sys/health"
    ca_path: /etc/ssl/Kubernetes_CA.pem
    method: GET
    validate_certs: false
    status_code: [429, 200, 501, 503]
    return_content: true
  register: output_status_vault

- name: Seated - print status
  debug:
    var: output_status_vault['json']['sealed']

- name: sealed is true
  when: output_status_vault['json']['sealed'] == true
  block:
    - name: Unseal
      ansible.builtin.uri:
        url: "https://127.0.0.1:8200/v1/sys/unseal"
        ca_path: /etc/ssl/Kubernetes_CA.pem
        method: POST
        validate_certs: false
        status_code: [429, 200, 501, 503]
        return_content: true
        body_format: json
        body:
          "key": "{{ item }}"
      register: testUnseal
      loop: "{{ hostvars['INIT_Vault_HOST']['keys'] }}"

    - name: Make sure service has time to init
      ansible.builtin.pause:
        seconds: 20


- name: Get config via root_token
  when: hostvars['INIT_Vault_HOST']['root_token'] is not false
  block:
    - name: GET status raft
      ansible.builtin.uri:
        url: "https://127.0.0.1:8200/v1/sys/storage/raft/configuration"
        ca_path: /etc/ssl/Kubernetes_CA.pem
        method: GET
        headers:
          X-Vault-Token: "{{ hostvars['INIT_Vault_HOST']['root_token'] }}"
        validate_certs: false
        status_code: [429, 200, 501, 503]
        return_content: true
      register: output_status_vault

    - name: Status raft
      ansible.builtin.debug:
        var: output_status_vault
