---
# handlers file for docker
  - name: Restart-service-docker
    ansible.builtin.service:
      name: docker
      state: restarted

  - name: Restart-systemd
    ansible.builtin.systemd_service:
      state: restarted
      daemon_reload: true
      name: docker
