repositories:
  - name: repo_docker
    url: https://download.docker.com/linux/debian/gpg
    state: present
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    filename: docker

  - name: repo_falco
    url:  https://falco.org/repo/falcosecurity-packages.asc
    state: present
    repo: deb https://download.falco.org/packages/deb stable main
    filename: falco

  - name: repo_trivi
    url:  https://aquasecurity.github.io/trivy-repo/deb/public.key
    state: present
    repo:  deb https://aquasecurity.github.io/trivy-repo/deb kinetic main
    filename: trivis
