- name: Download files
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{node_explorer['version']}}/node_exporter-{{node_explorer['version']}}.{{node_explorer['platform']}}.tar.gz"
    dest: "{{node_explorer['path']}}/"
    mode: 'u=rwx,g=rx,o=rx'
    checksum: "{{node_explorer['hash']}}"

- name: unarchive prometheus
  ansible.builtin.unarchive:
    src: "{{node_explorer['path']}}/node_exporter-{{node_explorer['version']}}.{{node_explorer['platform']}}.tar.gz"
    dest: "{{node_explorer['path']}}/"
    remote_src: yes

- name: Template a file to node_explorer
  ansible.builtin.template:
    src: node_explorer.service.j2
    dest: /etc/systemd/system/node_explorer.service
  notify: Restart node_explorer

- name: Enable service node_explorer
  ansible.builtin.systemd:
    name: node_explorer
    enabled: true
    daemon_reload: true
