- name: Install packages
  ansible.builtin.apt:
    update_cache: true
    allow_change_held_packages: true
    pkg:
      - bind9
      - bind9utils
      - bind9-doc

- name: Creates directory /var/lib/bind/zones
  ansible.builtin.file:
    path: /var/lib/bind/zones
    state: directory
    owner: bind
    group: bind
    mode: "0644"

- name: Template a file to dns.db2.j2
  ansible.builtin.template:
    src: dns.db2.j2
    dest: /var/lib/bind/{{ item.key }}.zone
    owner: bind
    group: bind
    mode: "0644"
  loop: "{{ domains | dict2items }}"
  notify:
    - Restart bind9

- name: Template a file to dns.db.j2
  ansible.builtin.template:
    src: dns.db.j2
    dest: /var/lib/bind/{{ domain }}.zone
    owner: bind
    group: bind
    mode: "0644"
  notify:
    - Restart bind9

- name: Copy a file to named.conf.options
  ansible.builtin.copy:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
    owner: bind
    group: bind
    mode: "0644"
  notify:
    - Restart bind9

- name: Copy a file to named.conf.local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: bind
    group: bind
    mode: "0644"
  notify:
    - Restart bind9

- name: Enable service bind9
  ansible.builtin.systemd:
    name: bind9
    enabled: true
    daemon_reload: true
    state: started
