## install BGP
- name: "[bird2] Install"
  ansible.builtin.package:
    name: bird2
    state: present

- name: Sysctl for bird2
  ansible.builtin.copy:
    mode: '0644'
    content: |
      net.ipv4.conf.all.forwarding=1
    dest: /etc/sysctl.d/98-bird2.conf

  notify:
    - sysctl--system

- name: "[bird] configuration file"
  ansible.builtin.template:
    mode: '0644'
    src: "bird.conf.j2"
    dest: "/etc/bird/bird.conf"

- name: "[{{ hostname }}] DEBUG birdc"
  ansible.builtin.include_tasks:
    file: _run_debug.yml
  vars:
    _CMD: "{{ item }}"
  loop:
    - birdc configure
    - birdc show protocols
